package com.example.mybatisplusdemo.mapper;

import com.example.mybatisplusdemo.model.dto.CourseCompletionDTO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface CourseCompletionMapper {

    @Select({
            "<script>",
            "SELECT * FROM (",
            "    SELECT",
            "        COALESCE(NULLIF(#{group1Course}, ''), '\\u5168\\u90e8\\u8bfe\\u7a0b') AS courseName,",
            "        COALESCE(NULLIF(#{group1College}, ''), '\\u5168\\u6821') AS college,",
            "        COALESCE(NULLIF(#{group1Semester}, ''), 'current') AS semester,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.task_point_id IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group1Course} IS NULL OR #{group1Course} = '' OR c.title = #{group1Course})",
            "              AND (#{group1College} IS NULL OR #{group1College} = '' OR #{group1College} = '\\u5168\\u6821' OR u.department_name = #{group1College})",
            "        ), 0), 2) AS taskCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.is_online = 1 THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group1Course} IS NULL OR #{group1Course} = '' OR c.title = #{group1Course})",
            "              AND (#{group1College} IS NULL OR #{group1College} = '' OR #{group1College} = '\\u5168\\u6821' OR u.department_name = #{group1College})",
            "        ), 0), 2) AS videoCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.task_point_id IS NOT NULL AND lr.check_in_time IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group1Course} IS NULL OR #{group1Course} = '' OR c.title = #{group1Course})",
            "              AND (#{group1College} IS NULL OR #{group1College} = '' OR #{group1College} = '\\u5168\\u6821' OR u.department_name = #{group1College})",
            "        ), 0), 2) AS quizCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.task_point_id IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group1Course} IS NULL OR #{group1Course} = '' OR c.title = #{group1Course})",
            "              AND (#{group1College} IS NULL OR #{group1College} = '' OR #{group1College} = '\\u5168\\u6821' OR u.department_name = #{group1College})",
            "        ), 0), 2) AS assignmentCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.check_in_time IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group1Course} IS NULL OR #{group1Course} = '' OR c.title = #{group1Course})",
            "              AND (#{group1College} IS NULL OR #{group1College} = '' OR #{group1College} = '\\u5168\\u6821' OR u.department_name = #{group1College})",
            "        ), 0), 2) AS examCompletionRate,",
            "        IFNULL((",
            "            SELECT COUNT(DISTINCT lr.task_point_id)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group1Course} IS NULL OR #{group1Course} = '' OR c.title = #{group1Course})",
            "              AND (#{group1College} IS NULL OR #{group1College} = '' OR #{group1College} = '\\u5168\\u6821' OR u.department_name = #{group1College})",
            "        ), 0) AS chapterStudyCount,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.check_in_time IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group1Course} IS NULL OR #{group1Course} = '' OR c.title = #{group1Course})",
            "              AND (#{group1College} IS NULL OR #{group1College} = '' OR #{group1College} = '\\u5168\\u6821' OR u.department_name = #{group1College})",
            "        ), 0), 2) AS checkinCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.task_point_id IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group1Course} IS NULL OR #{group1Course} = '' OR c.title = #{group1Course})",
            "        ), 0), 2) AS schoolTaskCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.is_online = 1 THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group1Course} IS NULL OR #{group1Course} = '' OR c.title = #{group1Course})",
            "        ), 0), 2) AS schoolVideoCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.task_point_id IS NOT NULL AND lr.check_in_time IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group1Course} IS NULL OR #{group1Course} = '' OR c.title = #{group1Course})",
            "        ), 0), 2) AS schoolQuizCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.task_point_id IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group1Course} IS NULL OR #{group1Course} = '' OR c.title = #{group1Course})",
            "        ), 0), 2) AS schoolAssignmentCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.check_in_time IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group1Course} IS NULL OR #{group1Course} = '' OR c.title = #{group1Course})",
            "        ), 0), 2) AS schoolExamCompletionRate,",
            "        IFNULL((",
            "            SELECT COUNT(DISTINCT lr.task_point_id)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group1Course} IS NULL OR #{group1Course} = '' OR c.title = #{group1Course})",
            "        ), 0) AS schoolChapterStudyCount,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.check_in_time IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group1Course} IS NULL OR #{group1Course} = '' OR c.title = #{group1Course})",
            "        ), 0), 2) AS schoolCheckinCompletionRate",
            "    UNION ALL",
            "    SELECT",
            "        COALESCE(NULLIF(#{group2Course}, ''), '\\u5168\\u90e8\\u8bfe\\u7a0b') AS courseName,",
            "        COALESCE(NULLIF(#{group2College}, ''), '\\u5168\\u6821') AS college,",
            "        COALESCE(NULLIF(#{group2Semester}, ''), 'current') AS semester,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.task_point_id IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group2Course} IS NULL OR #{group2Course} = '' OR c.title = #{group2Course})",
            "              AND (#{group2College} IS NULL OR #{group2College} = '' OR #{group2College} = '\\u5168\\u6821' OR u.department_name = #{group2College})",
            "        ), 0), 2) AS taskCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.is_online = 1 THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group2Course} IS NULL OR #{group2Course} = '' OR c.title = #{group2Course})",
            "              AND (#{group2College} IS NULL OR #{group2College} = '' OR #{group2College} = '\\u5168\\u6821' OR u.department_name = #{group2College})",
            "        ), 0), 2) AS videoCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.task_point_id IS NOT NULL AND lr.check_in_time IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group2Course} IS NULL OR #{group2Course} = '' OR c.title = #{group2Course})",
            "              AND (#{group2College} IS NULL OR #{group2College} = '' OR #{group2College} = '\\u5168\\u6821' OR u.department_name = #{group2College})",
            "        ), 0), 2) AS quizCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.task_point_id IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group2Course} IS NULL OR #{group2Course} = '' OR c.title = #{group2Course})",
            "              AND (#{group2College} IS NULL OR #{group2College} = '' OR #{group2College} = '\\u5168\\u6821' OR u.department_name = #{group2College})",
            "        ), 0), 2) AS assignmentCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.check_in_time IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group2Course} IS NULL OR #{group2Course} = '' OR c.title = #{group2Course})",
            "              AND (#{group2College} IS NULL OR #{group2College} = '' OR #{group2College} = '\\u5168\\u6821' OR u.department_name = #{group2College})",
            "        ), 0), 2) AS examCompletionRate,",
            "        IFNULL((",
            "            SELECT COUNT(DISTINCT lr.task_point_id)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group2Course} IS NULL OR #{group2Course} = '' OR c.title = #{group2Course})",
            "              AND (#{group2College} IS NULL OR #{group2College} = '' OR #{group2College} = '\\u5168\\u6821' OR u.department_name = #{group2College})",
            "        ), 0) AS chapterStudyCount,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.check_in_time IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group2Course} IS NULL OR #{group2Course} = '' OR c.title = #{group2Course})",
            "              AND (#{group2College} IS NULL OR #{group2College} = '' OR #{group2College} = '\\u5168\\u6821' OR u.department_name = #{group2College})",
            "        ), 0), 2) AS checkinCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.task_point_id IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group2Course} IS NULL OR #{group2Course} = '' OR c.title = #{group2Course})",
            "        ), 0), 2) AS schoolTaskCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.is_online = 1 THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group2Course} IS NULL OR #{group2Course} = '' OR c.title = #{group2Course})",
            "        ), 0), 2) AS schoolVideoCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.task_point_id IS NOT NULL AND lr.check_in_time IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group2Course} IS NULL OR #{group2Course} = '' OR c.title = #{group2Course})",
            "        ), 0), 2) AS schoolQuizCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.task_point_id IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group2Course} IS NULL OR #{group2Course} = '' OR c.title = #{group2Course})",
            "        ), 0), 2) AS schoolAssignmentCompletionRate,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.check_in_time IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group2Course} IS NULL OR #{group2Course} = '' OR c.title = #{group2Course})",
            "        ), 0), 2) AS schoolExamCompletionRate,",
            "        IFNULL((",
            "            SELECT COUNT(DISTINCT lr.task_point_id)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group2Course} IS NULL OR #{group2Course} = '' OR c.title = #{group2Course})",
            "        ), 0) AS schoolChapterStudyCount,",
            "        ROUND(IFNULL((",
            "            SELECT COUNT(DISTINCT CASE WHEN lr.check_in_time IS NOT NULL THEN lr.user_id END) * 100.0 / NULLIF(COUNT(DISTINCT lr.user_id), 0)",
            "            FROM learning_record lr",
            "            JOIN course c ON c.course_id = lr.course_id",
            "            JOIN `user` u ON u.id = lr.user_id AND u.role = 'student' AND u.is_deleted = 0",
            "            WHERE (#{group2Course} IS NULL OR #{group2Course} = '' OR c.title = #{group2Course})",
            "        ), 0), 2) AS schoolCheckinCompletionRate",
            ") t",
            "</script>"
    })
    List<CourseCompletionDTO> selectCompletions(
            @Param("group1College") String group1College,
            @Param("group2College") String group2College,
            @Param("group1Course") String group1Course,
            @Param("group2Course") String group2Course,
            @Param("group1Semester") String group1Semester,
            @Param("group2Semester") String group2Semester
    );
}