package com.example.mybatisplusdemo.mapper;

import com.example.mybatisplusdemo.model.dto.CourseAvgScoreDTO;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.List;

@Mapper
public interface CourseAvgScoresMapper {

    @Select({
            "<script>",
            "SELECT",
            "    g.course_name AS courseName,",
            "    g.college AS college,",
            "    COALESCE(NULLIF(#{semester}, ''), '\\u672a\\u533a\\u5206\\u5b66\\u671f') AS semester,",
            "    ROUND(g.avg_score_group, 2) AS avgScoreGroup,",
            "    ROUND(s.avg_score_school, 2) AS avgScoreSchool",
            "FROM (",
            "    SELECT",
            "        c.title AS course_name,",
            "        u.department_name AS college,",
            "        AVG(st.average_course_scores) AS avg_score_group",
            "    FROM (SELECT DISTINCT course_id, user_id FROM learning_record) lr",
            "    JOIN student st ON st.student_id = lr.user_id",
            "    JOIN `user` u ON u.id = st.student_id AND u.role = 'student' AND u.is_deleted = 0",
            "    JOIN course c ON c.course_id = lr.course_id",
            "    WHERE st.average_course_scores IS NOT NULL",
            "      AND (#{college} IS NULL OR u.department_name = #{college})",
            "    GROUP BY c.title, u.department_name",
            ") g",
            "JOIN (",
            "    SELECT",
            "        c.title AS course_name,",
            "        AVG(st.average_course_scores) AS avg_score_school",
            "    FROM (SELECT DISTINCT course_id, user_id FROM learning_record) lr",
            "    JOIN student st ON st.student_id = lr.user_id",
            "    JOIN `user` u ON u.id = st.student_id AND u.role = 'student' AND u.is_deleted = 0",
            "    JOIN course c ON c.course_id = lr.course_id",
            "    WHERE st.average_course_scores IS NOT NULL",
            "    GROUP BY c.title",
            ") s ON s.course_name = g.course_name",
            "UNION ALL",
            "SELECT",
            "    s.course_name AS courseName,",
            "    '\\u5168\\u6821' AS college,",
            "    COALESCE(NULLIF(#{semester}, ''), '\\u672a\\u533a\\u5206\\u5b66\\u671f') AS semester,",
            "    ROUND(s.avg_score_school, 2) AS avgScoreGroup,",
            "    ROUND(s.avg_score_school, 2) AS avgScoreSchool",
            "FROM (",
            "    SELECT",
            "        c.title AS course_name,",
            "        AVG(st.average_course_scores) AS avg_score_school",
            "    FROM (SELECT DISTINCT course_id, user_id FROM learning_record) lr",
            "    JOIN student st ON st.student_id = lr.user_id",
            "    JOIN `user` u ON u.id = st.student_id AND u.role = 'student' AND u.is_deleted = 0",
            "    JOIN course c ON c.course_id = lr.course_id",
            "    WHERE st.average_course_scores IS NOT NULL",
            "    GROUP BY c.title",
            ") s",
            "ORDER BY courseName, college",
            "</script>"
    })
    List<CourseAvgScoreDTO> selectCourseAvgScores(@Param("college") String college, @Param("semester") String semester);

    @Select({
            "<script>",
            "SELECT",
            "    g.course_name AS courseName,",
            "    g.college AS college,",
            "    g.semester AS semester,",
            "    ROUND(g.avg_score_group, 2) AS avgScoreGroup,",
            "    ROUND(s.avg_score_school, 2) AS avgScoreSchool",
            "FROM (",
            "    SELECT",
            "        c.title AS course_name,",
            "        u.department_name AS college,",
            "        COALESCE(dt.term_name, '\\u672a\\u77e5\\u5b66\\u671f') AS semester,",
            "        AVG(fcs.final_score) AS avg_score_group",
            "    FROM fact_course_score fcs",
            "    JOIN course c ON c.course_id = fcs.course_id",
            "    JOIN `user` u ON u.id = fcs.student_id AND u.role = 'student' AND u.is_deleted = 0",
            "    LEFT JOIN dim_term dt ON dt.term_id = fcs.term_id",
            "    WHERE (#{college} IS NULL OR u.department_name = #{college})",
            "      AND (",
            "            #{semester} IS NULL OR #{semester} = ''",
            "            OR dt.term_name = #{semester}",
            "            OR dt.term_code = #{semester}",
            "            OR dt.term_name LIKE CONCAT('%', #{semester}, '%')",
            "          )",
            "    GROUP BY c.title, u.department_name, COALESCE(dt.term_name, '\\u672a\\u77e5\\u5b66\\u671f')",
            ") g",
            "JOIN (",
            "    SELECT",
            "        c.title AS course_name,",
            "        COALESCE(dt.term_name, '\\u672a\\u77e5\\u5b66\\u671f') AS semester,",
            "        AVG(fcs.final_score) AS avg_score_school",
            "    FROM fact_course_score fcs",
            "    JOIN course c ON c.course_id = fcs.course_id",
            "    JOIN `user` u ON u.id = fcs.student_id AND u.role = 'student' AND u.is_deleted = 0",
            "    LEFT JOIN dim_term dt ON dt.term_id = fcs.term_id",
            "    WHERE (",
            "            #{semester} IS NULL OR #{semester} = ''",
            "            OR dt.term_name = #{semester}",
            "            OR dt.term_code = #{semester}",
            "            OR dt.term_name LIKE CONCAT('%', #{semester}, '%')",
            "          )",
            "    GROUP BY c.title, COALESCE(dt.term_name, '\\u672a\\u77e5\\u5b66\\u671f')",
            ") s ON s.course_name = g.course_name AND s.semester = g.semester",
            "UNION ALL",
            "SELECT",
            "    s.course_name AS courseName,",
            "    '\\u5168\\u6821' AS college,",
            "    s.semester AS semester,",
            "    ROUND(s.avg_score_school, 2) AS avgScoreGroup,",
            "    ROUND(s.avg_score_school, 2) AS avgScoreSchool",
            "FROM (",
            "    SELECT",
            "        c.title AS course_name,",
            "        COALESCE(dt.term_name, '\\u672a\\u77e5\\u5b66\\u671f') AS semester,",
            "        AVG(fcs.final_score) AS avg_score_school",
            "    FROM fact_course_score fcs",
            "    JOIN course c ON c.course_id = fcs.course_id",
            "    JOIN `user` u ON u.id = fcs.student_id AND u.role = 'student' AND u.is_deleted = 0",
            "    LEFT JOIN dim_term dt ON dt.term_id = fcs.term_id",
            "    WHERE (",
            "            #{semester} IS NULL OR #{semester} = ''",
            "            OR dt.term_name = #{semester}",
            "            OR dt.term_code = #{semester}",
            "            OR dt.term_name LIKE CONCAT('%', #{semester}, '%')",
            "          )",
            "    GROUP BY c.title, COALESCE(dt.term_name, '\\u672a\\u77e5\\u5b66\\u671f')",
            ") s",
            "ORDER BY semester DESC, courseName, college",
            "</script>"
    })
    List<CourseAvgScoreDTO> selectCourseAvgScoresFromFact(@Param("college") String college, @Param("semester") String semester);
}
